[package]
name = "board"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitfield-struct = "0.13.0"
derive_more = { version = "2", default-features = false, features = ["display", "from_str"] }
enum-map = "3"
enumset = { version = "1", default-features = false }
fen = { version = "0.1.0", path = "../fen" }
itertools = { version = "0.14", default-features = false }
strum = { version = "0.28", default-features = false, features = ["derive"] }

[lints]
workspace = true

[dev-dependencies]
proptest = "1"
