[package]
name = "board"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arrayvec = { version = "0.7", default-features = false }
derive_more = { version = "2", default-features = false, features = ["add", "add_assign", "display", "from_str", "sum"] }
enum-map = "3"
enum_dispatch = "0.3"
enumset = { version = "1", default-features = false }
fen = { version = "0.1.0", path = "../fen" }
itertools = { version = "0.14", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
strum = { version = "0.28", default-features = false, features = ["derive"] }

[features]
serde = ["dep:serde"]

[lints]
workspace = true

[dev-dependencies]
proptest = "1"
