#![cfg_attr(not(test), no_std)]

mod bitboard;
mod board;
mod castling_right;
mod castling_rights;
mod castling_squares;
mod chess_move;
mod color;
mod diagonal;
mod direction;
mod file;
mod fullmove_number;
mod halfmove_clock;
mod leaper;
mod orthogonal;
mod piece;
mod piece_kind;
mod piece_placement;
mod promotion_piece;
mod rank;
mod slider;
mod square;
mod square_iter;
mod subset_iter;

pub use bitboard::Bitboard;
pub use board::Board;
pub use castling_right::CastlingRight;
pub use castling_rights::CastlingRights;
pub use castling_squares::CastlingSquares;
pub use chess_move::{Castling, ChessMove, DoublePush, EnPassant, MoveKind, Normal, Promotion};
pub use color::Color;
pub use diagonal::Diagonal;
pub use direction::Direction;
pub use file::File;
pub use fullmove_number::FullmoveNumber;
pub use halfmove_clock::HalfmoveClock;
pub use leaper::{BlackPawn, King, Knight, Leaper, Leaps, Pawn, WhitePawn};
pub use orthogonal::Orthogonal;
pub use piece::Piece;
pub use piece_kind::PieceKind;
pub use piece_placement::{Lifted, PiecePlacement};
pub use promotion_piece::PromotionPiece;
pub use rank::Rank;
pub use slider::{Bishop, Magic, Rays, Rook, Slider};
pub use square::Square;
pub use square_iter::SquareIter;
pub use subset_iter::SubsetIter;
