#![cfg_attr(not(test), no_std)]

mod bitboard;
mod board;
mod castling_right;
mod castling_rights;
mod castling_squares;
mod chess_move;
mod color;
mod diagonal;
mod direction;
mod file;
mod fullmove_number;
mod halfmove_clock;
mod king_safety;
mod leaper;
mod move_generator;
mod orthogonal;
mod perft_position;
mod piece;
mod piece_kind;
mod placement;
mod promotion_piece;
mod rank;
mod slider;
mod split_mix;
mod square;
mod square_iter;
mod state;
mod subset_iter;
mod zobrist;
mod zobrist_keys;

pub use bitboard::Bitboard;
pub use board::{Board, MoveList};
pub use castling_right::CastlingRight;
pub use castling_rights::CastlingRights;
pub use castling_squares::CastlingSquares;
pub use chess_move::{Castling, ChessMove, DoublePush, EnPassant, MoveKind, Normal, Promotion};
pub use color::Color;
pub use diagonal::Diagonal;
pub use direction::Direction;
pub use file::File;
pub use fullmove_number::FullmoveNumber;
pub use halfmove_clock::HalfmoveClock;
pub use king_safety::KingSafety;
pub use leaper::{BlackPawn, King, Knight, Leaper, Leaps, Pawn, WhitePawn};
pub use move_generator::MoveGenerator;
pub use orthogonal::Orthogonal;
pub use perft_position::PerftPosition;
pub use piece::Piece;
pub use piece_kind::PieceKind;
pub use placement::{Empty, Hand, Holding, PiecePlacement, Placement};
pub use promotion_piece::PromotionPiece;
pub use rank::Rank;
pub use slider::{Bishop, Magic, Rays, Rook, Slider};
pub use square::Square;
pub use square_iter::SquareIter;
pub use state::State;
pub use subset_iter::SubsetIter;
pub use zobrist::Zobrist;
