[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
board = { path = "../crates/board" }
enum-map = "3"
proc-macro2 = { version = "1", features = ["span-locations"] }
rustc_lexer = { package = "ra-ap-rustc_lexer", version = "0.174.0" }
strum = { version = "0.28", features = ["derive"] }
syn = { version = "2", features = ["full", "parsing", "visit"] }

[lints]
workspace = true
