[package]
name = "uci"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
board = { version = "0.1.0", path = "../board" }
derive_more = { version = "2", default-features = false, features = ["display", "from_str"] }
eval = { version = "0.1.0", path = "../eval" }
itertools = { version = "0.14", default-features = false }
proptest = { version = "1", optional = true }
search = { version = "0.1.0", path = "../search" }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
strum = { version = "0.28", default-features = false, features = ["derive"] }
thiserror = { version = "2", default-features = false }

[features]
proptest = ["dep:proptest", "board/proptest", "eval/proptest", "search/proptest"]
serde = ["dep:serde"]

[lints]
workspace = true

[dev-dependencies]
board = { version = "0.1.0", path = "../board", features = ["proptest"] }
eval = { version = "0.1.0", path = "../eval", features = ["proptest"] }
proptest = "1"
search = { version = "0.1.0", path = "../search", features = ["proptest"] }
