[package]
name = "uci"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
board = { version = "0.1.0", path = "../board" }
eval = { version = "0.1.0", path = "../eval" }
search = { version = "0.1.0", path = "../search" }
strum = { version = "0.28", default-features = false, features = ["derive"] }
thiserror = { version = "2", default-features = false }

[lints]
workspace = true
