exclude_globs = [
    "xtask/**",
    "crates/*/src/main.rs",
    "crates/chess/**",
    "crates/tui/**",
    "crates/board/src/slider/magics.rs",
    "crates/eval/src/piece_square_tables/placement_table.rs",
]
test_workspace = true
additional_cargo_args = ["--lib"]
minimum_test_timeout = 10.0
cap_lints = false
