[package]
name = "eval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
board = { version = "0.1.0", path = "../board" }
derive_more = { version = "2", default-features = false, features = ["add", "display", "not"] }
enum-map = "3"
strum = { version = "0.28", default-features = false }

[lints]
workspace = true
