[package]
name = "arena"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
board = { version = "0.1.0", path = "../board" }
clap = { version = "4", features = ["derive"] }
engine = { version = "0.1.0", path = "../engine" }
derive_more = { version = "2", features = ["display", "from_str"] }
thiserror = "2"
strum = { version = "0.28", default-features = false, features = ["derive"] }
uci = { version = "0.1.0", path = "../uci" }

[dev-dependencies]
search = { version = "0.1.0", path = "../search" }

[lints]
workspace = true
