name: Stack

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

concurrency:
  group: stack-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stacked:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.98.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo xtask stacked
        env:
          GH_TOKEN: ${{ github.token }}
          BASE_REF: ${{ github.base_ref }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
